services:    
  foxglove:
    image: alang6154/foxglove:latest
    build:
      context: .
      dockerfile: foxglove.Dockerfile
      args:
        UID: ${HOST_UID}
        GID: ${HOST_GID}
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix         # Para las interfaces graficas -> Ejecutar xhost +
      - /etc/machine-id:/etc/machine-id       # Ejecutar dbus-uuidgen --ensure=/etc/machine-id en host
    stdin_open: true                          # docker run -t

  roshumble:
    image: alang6154/cppdev:latest
    build:
      context: .
      dockerfile: cppdev.Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
      - TELFOX_PATH=/home/nonroot/telfox
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix         # Para las interfaces graficas -> Ejecutar xhost +
      - /etc/machine-id:/etc/machine-id       # Ejecutar dbus-uuidgen --ensure=/etc/machine-id en host
      - ../:/home/nonroot/telfox # Creamos un bind-mount de la carpeta actual
    stdin_open: true                          # docker run -t
    command: ["/bin/bash"]
